/**
 * Projeto Vinhos Portugueses
 */

let vinho = [{ nomeVinho: 'Crasto Superior',
                produtor: 'Quinta do Crasto',
                safra: 2018,
                regiao: 'Douro',
                tipo: 'Tinto',
                tempServico: 16,
                isDecantacao: true,
                tempoDecantacao: 60,
                teorAlcoolico: 14,
                uva: ['Sousão', 'Tinta Roriz', 'Touriga Franca', 'Touriga Nacional'] },
              
              { nomeVinho: 'Monte Velho',
                produtor: 'Herdade do Esporão',
                safra: 2017,
                regiao: 'Alentejo',
                tipo: 'Tinto',
                tempServico: 15, 
                isDecantacao: true,
                tempoDecantacao: 20,
                teorAlcoolico: 14,
                uva: ['Aragonêz', 'Syrah', 'Touriga Nacional', 'Trincadeira'] },

              { nomeVinho: 'Cartuxa',
                produtor: 'Fundação Eugénio de Almeida',
                safra: 2016,
                regiao: 'Alentejo',
                tipo: 'Tinto',
                tempServico: 18,
                isDecantacao: true,
                tempoDecantacao: 30,
                teorAlcoolico: 14.5,
                uva: ['Alicante Bouschet', 'Aragonêz'] },
              { nomeVinho: 'Monarkia das Marias', 
                produtor: 'Quinta do Monte d Oiro', 
                safra: 2019,
                regiao: 'Lisboa',
                tipo: 'Branco',
                tempServico: 11,
                isDecantacao: false,
                tempoDecantacao: 0,
                teorAlcoolico: 13,
                uva: ['Arinto', 'Fernão-Pires', 'Viognier'] },
              { nomeVinho: 'Scala Coeli',
                produtor: 'Fundação Eugénio de Almeida',
                safra: 2018,
                regiao: 'Alentejo',
                tipo: 'Branco',
                tempServico: 7,
                isDecantacao: false,
                tempoDecantacao: 0,
                teorAlcoolico: 12.5,
                uva: ['Verdelho'] },
              { nomeVinho: 'Palácio da Brejoeira',
                produtor: 'Palácio da Brejoeira',
                safra: 2019,
                regiao: 'Minho',
                tipo: 'Branco',
                tempServico: 9,
                isDecantacao: false,
                tempoDecantacao: 0,
                teorAlcoolico: 13,
                uva: ['Alvarinho'] },
              { nomeVinho: 'Cálem Vintage',
                produtor: 'Sogevinus Fine Wines', 
                safra: 2019,
                regiao: 'Douro',
                tipo: 'Porto',
                tempServico: 18,
                isDecantacao: false,
                tempoDecantacao: 0,
                teorAlcoolico: 20,
                uva: ['Sousão', 'Tinta Roriz', 'Touriga Franca', 'Touriga Nacional'] }
            ]    
              //papa figos
          // Quinta do vale Meão]

console.log(vinho);


